# Generated by Django 5.2.3 on 2025-06-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenmenu',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Dernier jour de la semaine'),
        ),
        migrations.AlterField(
            model_name='canteenmenu',
            name='date',
            field=models.DateField(verbose_name='Date du premier jour de la semaine'),
        ),
    ]
