# Generated by Django 5.2.3 on 2025-06-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_canteenmenu_end_date_alter_canteenmenu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteenmenu',
            name='end_date',
            field=models.DateField(verbose_name='Dernier jour de la semaine'),
        ),
    ]
