# Generated by Django 5.2.3 on 2025-06-26 12:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationpage',
            name='summary',
            field=wagtail.fields.RichTextField(default='test', max_length=255, verbose_name='Résumé'),
            preserve_default=False,
        ),
    ]
