# Generated by Django 5.2.3 on 2025-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_alter_associationpage_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationpage',
            name='summary',
            field=models.CharField(help_text="Bref résumé de l'association", max_length=170, verbose_name='Résumé'),
        ),
    ]
