# Generated by Django 5.2.3 on 2025-06-26 12:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_alter_associationpage_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationpage',
            name='summary',
            field=wagtail.fields.RichTextField(help_text="Bref résumé de l'association", max_length=170, verbose_name='Résumé'),
        ),
    ]
