# Generated by Django 5.2.3 on 2025-06-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(choices=[('external', 'Externe'), ('internal', 'Interne')], default='internal', max_length=20, verbose_name="Type d'événement"),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='localisation',
            field=models.CharField(max_length=255, verbose_name='Localisation'),
        ),
    ]
