# Generated by Django 5.2.3 on 2025-06-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventpage_event_type_alter_eventpage_localisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'organisateur")),
            ],
            options={
                'verbose_name': 'Organisateur',
            },
        ),
        migrations.AddField(
            model_name='eventpage',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.organizer', verbose_name='Organisateur'),
        ),
    ]
