# Generated by Django 5.2.3 on 2025-06-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventorganizerinline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorganizerinline',
            name='page',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.organizer', verbose_name='Organisateur'),
        ),
        migrations.DeleteModel(
            name='EventOrganizer',
        ),
        migrations.DeleteModel(
            name='EventOrganizerInline',
        ),
    ]
