# Generated by Django 5.2.3 on 2025-06-18 14:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmeeting', '0002_alter_councilmeetingpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmeetingpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('document', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}),
        ),
    ]
