# Generated by Django 5.2.3 on 2025-06-18 14:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmeeting', '0003_alter_councilmeetingpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmeetingpage',
            name='body',
            field=wagtail.fields.StreamField([('document', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}),
        ),
    ]
