# Generated by Django 5.2.3 on 2025-06-18 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmeeting', '0004_alter_councilmeetingpage_body'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='councilmeetingpage',
            name='body',
        ),
        migrations.AddField(
            model_name='councilmeetingpage',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document', verbose_name='Compte rendu de la réunion'),
        ),
    ]
