# Generated by Django 5.2.3 on 2025-06-18 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmeeting', '0005_remove_councilmeetingpage_body_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmeetingpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document', verbose_name='Compte rendu de la réunion'),
        ),
    ]
