# Generated by Django 5.2.3 on 2025-06-18 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmeeting', '0006_alter_councilmeetingpage_document'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la réunion')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document', verbose_name='Compte rendu de la réunion')),
            ],
        ),
        migrations.DeleteModel(
            name='CouncilMeetingPage',
        ),
    ]
