# Generated by Django 5.2.3 on 2025-06-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmeeting', '0007_councilmeeting_delete_councilmeetingpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='councilmeeting',
            options={'ordering': ['-date'], 'verbose_name': 'Réunion du conseil municipal', 'verbose_name_plural': 'Réunions du conseil municipal'},
        ),
    ]
