# Generated by Django 5.2.3 on 2025-06-18 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilmeeting', '0008_alter_councilmeeting_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='councilmeeting',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
    ]
